Zed-CSP/dangerForce-Proj-1

assets/js/script.js
add the function to obtain the latitude and longitude values for the selected city
=> function to obtain the latitude and longitude values for the city

assets/js/script.js
Add function to call the air pollution API and generate HTML elements with the data
=> Add function to call API to get/display pollution data

assets/js/script.js
Add function to display gif based on AQI of the city searched
=> Add function to display gif

assets/js/script.js
Add getGiphy function call to getPollution function and add comments to getGiphy function
=> Call giphy function, add comments.

index.html
moved lines 12-20 in HTML to CSS stylesheet (lines 4-8)
=> Move style to css

assets/css/style.css, index.html
corrected tailwind cdn link in HTML (line 8)
added grid classes to HTML elements
=> Update tailwind link

assets/css/style.css
I changed the title in style.css
=> Change title size

index.html
add grid rows to html elements for spacing
=> Add grid rows

assets/js/script.js
In case the city name entered by the user results in undefined data from the openweathermap API, the application will trigger a function to display a modal alert informing the user. Mentioned function will be included in the next code update.
=> Check if API responding with a valid data based on the user's city name.

assets/js/script.js
An event listener has been added to the history button elements which retrieves the longitude and latitude values for the particular city from the array of objects stored in the local storage. The function then invokes getPollution() while passing these values as arguments, in order to retrieve the pollution data corresponding to the selected city.
The history buttons now have a class attribute of 'history-btn' assigned to them within createCityButton() that generates history buttons.
A conditional statement has been added to ensure that the code is executed only when the selected button element has a class of 'history-btn' . The code will now check if the classList of the clicked button element contains the class 'history-btn', rather than checking its parent container. It ensures that …
=> Responsive history buttons

assets/css/style.css
The font size and line-height in the modal box have been adjusted to a fluid design by implementing a formula. This formula calculates the font size and line-height based on the viewport width, resulting in an adaptive design that adjusts to various device screen sizes.
=> Change modal box font size and line-height to fluid.

assets/css/style.css, assets/js/script.js
To ensure that the user inputs a value, a check has been implemented to verify that the input field contains some value when they click on the "Get Pollution" button. If the input field is empty, a modal alert will notify the user.
=> Check if user enters input value.

assets/js/library.js, assets/js/script.js, index.html
createsa library file for gify
=> gify library file

assets/css/style.css
changed title color and added pin icon
=> Change color

assets/css/style.css, index.html
re-set grid rows and columns for all elements
=> Add element cards

index.html
adjusted placement of items in title and form cards
=> Card content placement

assets/css/style.css, assets/js/script.js
- Add condition in search button event listener for multiple cities returned to bring up modal message
- Add modal message to have the user clarify which city they want to search
- Run search based on what city they choose
=> Add handling for multiple cities returned

assets/css/style.css, index.html
adjusted line height and button color for landing cards
=> Card styling

assets/css/style.css, index.html
center search card and move "how to sneeze" to a separate card under the title
=> Card location update

index.html
formatted to make the parents and children easier to see
=> format html with prettier

README.md
Add sections to README: General Info, Preview, Features, Tech Used, User Story, Acceptance Criteria
=> Add user stories

assets/js/script.js
Remove unnecessary line breaks from script.js
=> Remove unnecessary line breaks

assets/css/style.css, index.html
mobile-layout; still need to address overscroll for pollution container and tissue box
=> Responsive design

assets/js/script.js
Refactor the 'add event listener' function for the search button into several individual functions that perform specific tasks, and then call them sequentially.
=> Refactor the 'add event listener' function for the search button.

index.html
Remove space in ID that was causing event listener to break
=> Remove erroneous space in id

assets/js/script.js
Change http to https for request urls to prevent errors on deployment
=> Change http to https for request urls

assets/css/style.css, index.html
resize header text for medium and large screens
=> Resize header text

assets/js/script.js
Refactor the `saveSearchHistory` function into several individual functions that perform specific tasks, and then call them sequentially, instead of having all this functionality within the one function.
=> Refactor the `saveSearchHistory` function into several individual functions.

assets/css/style.css
remove old selectors that were transitioned to tailwind css
=> Remove css comments

assets/js/script.js
Remove console.log() statements from script.js
=> Remove console.log statements

assets/css/style.css, index.html
- Update clear button styles so it does not touch bottom of container or span entire width of container
- Remove the underline from the location-btn class, including when hovering, for aesthetic purposes
- Clean up css indentation--missing in some places, extra in others
- Remove extra line breaks
=> Style clear button

assets/js/script.js
Fix bug where AQI was showing units that don't apply to it
=> Fix bug where aqi is showing units

README.md
- Add gif showing preview of application to README
- Add deployed app link to README
=> Add preview gif. Update readme with deployed app info.
